---
- name: Reset lab to default configlet profile
  hosts: cvp2

  vars_files:
    - ../vars/CVP_model.yml
  tasks:
    - name: Upload dummy configlet
      arista.cvp.cv_configlet_v3:
        configlets: "{{ CVP_CONFIGLETS }}"

    - name: Build default container topology
      arista.cvp.cv_container_v3:
        topology: "{{ CONTAINERS_DUMMY }}"
        apply_mode: strict

    - name: Build default container topology
      arista.cvp.cv_container_v3:
        topology: "{{ CONTAINERS_DEFAULT }}"
        apply_mode: strict

    - name: Apply configlets for default config
      arista.cvp.cv_device_v3:
        devices: "{{ CVP_DEVICES_DEFAULT }}"
        state: present
        apply_mode: strict
      register: APPLY_RESULTS

    # - name: Validate configlets
    #   arista.cvp.cv_validate_v3:
    #     validate_mode: ignore
    #     devices: "{{ VALIDATE_DEVICES }}"

    - name: Get all pending tasks from CVP
      arista.cvp.cv_facts:
        facts:
        - tasks
      register: pending_tasks

    - name: Apply all pending tasks
      arista.cvp.cv_task:
        action: apply
        task_ids: "{{ pending_tasks.ansible_facts.tasks | map(attribute='workOrderId') | list }}"
      when: pending_tasks.ansible_facts.tasks | length > 0

    - name: Query task completion
      arista.cvp.cv_task_v3:
        state: query
        task_id: "{{ APPLY_RESULTS.taskIds }}"  # Referencing APPLY_RESULTS for task ID
      register: task_status

    - name: Debug APPLY_RESULTS
      debug:
        msg: "{{ APPLY_RESULTS }}"



