---
tenants:
  - name: ACME
    mac_vrf_vni_base: 10000
    vrfs:
      - name: VRF_A
        vrf_vni: 10
        svis:
          - id: 10
            name: DMZ-1
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          - id: 20
            name: Internal-1
            enabled: true
            ip_address_virtual: 10.1.20.1/24
          - id: 30
            name: Staging-1 
            enabled: true
            ip_address_virtual: 10.1.30.1/24
        l3_interfaces:
          - interfaces: [Ethernet9]
            ip_addresses: [10.1.5.1/24]
            nodes: [borderleaf1]
            enabled: True 
        bgp_peers:
          - ip_address: 10.1.5.254
            remote_as: 1
            nodes: [borderleaf1]
      - name: VRF_B
        vrf_vni: 20
        svis:
          - id: 40
            name: DMZ-2
            enabled: true
            ip_address_virtual: 10.2.10.1/24
          - id: 50
            name: Internal-2
            enabled: true
            ip_address_virtual: 10.2.20.1/24
          - id: 60
            name: Staging-2
            enabled: true
            ip_address_virtual: 10.2.30.1/24
        l3_interfaces:
          - interfaces: [Ethernet9]
            ip_addresses: [10.1.6.1/24]
            nodes: [borderleaf2]
            enabled: True 
        bgp_peers:
          - ip_address: 10.1.6.254
            remote_as: 2
            nodes: [borderleaf2]      